<option value="">Seleccione Provincia</option>
                        <option value="CAPITAL FEDERAL">Capital Federal</option>
                        <option value="BUENOS AIRES">Buenos Aires</option>
                        <option value="CATAMARCA">Catamarca</option>
                        <option value="CORDOBA">Cordoba</option>
                        <option value="CORRIENTES">Corrientes</option>
                        <option value="CHACO">Chaco</option>
                        <option value="CHUBUT">Chubut</option>
                        <option value="ENTRE RIOS">Entre Rios</option>
                        <option value="FORMOSA">Formosa</option>
                        <option value="JUJUY">Jujuy</option>
                        <option value="LA PAMPA">La Pampa</option>
                        <option value="LA RIOJA">La Rioja</option>
                        <option value="MENDOZA">Mendoza</option>
                        <option value="MISIONES">Misiones</option>
                        <option value="NEUQUEN">Neuquen</option>
                        <option value="RIO NEGRO">Rio Negro</option>
                        <option value="SALTA">Salta</option>
                        <option value="SAN JUAN">San Juan</option>
                        <option value="SAN LUIS">San Luis</option>
                        <option value="SANTA CRUZ">Santa Cruz</option>
                        <option value="SANTA FE">Santa Fe</option>
                        <option value="TIERRA DEL FUEGO">Tierra Del Fuego</option>
                        <option value="TUCUMAN">Tucuman</option>